import { ChevronDown, ChevronUp } from 'lucide-react'
import { useState } from 'react'
import type { LearningPathOption, UploadConfig } from '@/utils/types/upload'

type Props = {
  config: UploadConfig
  pathOptions: LearningPathOption[]
  pathLoading?: boolean
  kpOptions: Array<{ id: string; name: string }>
  kpLoading?: boolean
  kpKeyword: string
  onKpKeywordChange: (v: string) => void
  onChange: (patch: Partial<UploadConfig>) => void
  autoGenerateDisabled?: boolean
}

export default function UploadConfigPanel({
  config,
  pathOptions,
  pathLoading,
  kpOptions,
  kpLoading,
  kpKeyword,
  onKpKeywordChange,
  onChange,
  autoGenerateDisabled,
}: Props) {
  const [expanded, setExpanded] = useState(false)

  return (
    <section className="rounded-[18px] border border-[#E6EEFA] bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]">
      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        className="flex w-full items-center justify-between px-5 py-4 text-left"
      >
        <div>
          <h2 className="text-sm font-bold text-[#0F2A5F]">高级上传配置</h2>
          <p className="mt-0.5 text-xs text-[#64748B]">关联路径、知识点与 AI 解析选项</p>
        </div>
        {expanded ? (
          <ChevronUp className="h-4 w-4 text-[#64748B]" />
        ) : (
          <ChevronDown className="h-4 w-4 text-[#64748B]" />
        )}
      </button>

      {expanded ? (
        <div className="border-t border-[#EEF3FA] px-5 pb-5 pt-4">
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <div>
              <label className="mb-2 block text-xs font-semibold text-[#64748B]">关联学习路径</label>
              <select
                value={config.learningPathId || ''}
                disabled={pathLoading}
                onChange={(e) => onChange({ learningPathId: e.target.value || undefined })}
                className="h-10 w-full rounded-xl border border-[#E6EEFA] bg-[#F8FBFF] px-3 text-sm outline-none focus:border-[#93C5FD]"
              >
                <option value="">
                  {pathOptions.length === 0 ? '暂无学习路径，可先上传资料' : '不关联路径'}
                </option>
                {pathOptions.map((p) => (
                  <option key={p.id} value={p.id}>{p.title}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="mb-2 block text-xs font-semibold text-[#64748B]">关联知识点</label>
              <input
                value={kpKeyword}
                onChange={(e) => onKpKeywordChange(e.target.value)}
                placeholder="搜索知识点..."
                className="mb-2 h-9 w-full rounded-lg border border-[#E6EEFA] px-3 text-sm outline-none focus:border-[#93C5FD]"
              />
              <select
                multiple
                disabled={kpLoading}
                value={config.knowledgePointIds || []}
                onChange={(e) => {
                  const selected = Array.from(e.target.selectedOptions).map((o) => o.value)
                  onChange({ knowledgePointIds: selected })
                }}
                className="h-20 w-full rounded-xl border border-[#E6EEFA] bg-[#F8FBFF] px-3 text-sm outline-none"
              >
                {kpOptions.map((kp) => (
                  <option key={kp.id} value={kp.id}>{kp.name}</option>
                ))}
              </select>
            </div>

            <div className="flex items-center justify-between rounded-xl border border-[#EEF3FA] bg-[#F8FBFF] px-4 py-3">
              <div>
                <p className="text-sm font-semibold text-[#334155]">自动 AI 解析</p>
                <p className="text-xs text-[#64748B]">上传后自动提取摘要与知识点</p>
              </div>
              <button
                type="button"
                onClick={() => onChange({ autoParse: !config.autoParse })}
                className={`h-7 w-12 rounded-full transition ${
                  config.autoParse ? 'bg-[#2563EB]' : 'bg-[#CBD5E1]'
                }`}
              >
                <span
                  className={`block h-6 w-6 rounded-full bg-white shadow transition ${
                    config.autoParse ? 'translate-x-5' : 'translate-x-0.5'
                  }`}
                />
              </button>
            </div>

            <div className="flex items-center justify-between rounded-xl border border-[#EEF3FA] bg-[#F8FBFF] px-4 py-3">
              <div>
                <p className="text-sm font-semibold text-[#334155]">自动生成学习资源</p>
                <p className="text-xs text-[#64748B]">
                  {autoGenerateDisabled ? '待后端接口支持' : '解析完成后自动生成'}
                </p>
              </div>
              <button
                type="button"
                disabled={autoGenerateDisabled}
                onClick={() => onChange({ autoGenerateResource: !config.autoGenerateResource })}
                className={`h-7 w-12 rounded-full transition disabled:opacity-40 ${
                  config.autoGenerateResource ? 'bg-[#2563EB]' : 'bg-[#CBD5E1]'
                }`}
              >
                <span
                  className={`block h-6 w-6 rounded-full bg-white shadow transition ${
                    config.autoGenerateResource ? 'translate-x-5' : 'translate-x-0.5'
                  }`}
                />
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </section>
  )
}
